@startuml zohan-c4-container-diagram
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define MATERIAL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/nodejs.puml
!include DEVICONS/react.puml
!include DEVICONS/mongodb.puml
!include MATERIAL/map.puml
!include MATERIAL/mail.puml
!include FONTAWESOME/server.puml

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

Person(user, "Přihlášený uživatel", "Uživatel, který může vytvářet rezervace a spravovat své údaje.")
Person(public, "Nepřihlášený uživatel", "Uživatel, který nemá účet a může jen prohlížet veřejné informace.")
Person(admin, "Zaměstnanec", "Uživatel administračního rozhraní, který může spravovat obchodní profil a její rezervace.")

System_Boundary(zohan_system, "Rezervační systém") {
    Container(spa_user, "SPA pro uživatele", "React, Next.js", "Single-page aplikace pro běžné uživatele. Aplikace umožňuje prohlížet veřejné informace a vytvářet rezervace.", "react")
    Container(spa_admin, "SPA pro administrátory", "React, Next.js", "Single-page aplikace pro zaměstnance. Aplikace umožňuje spravovat obchodní profil a rezervace.", "react")
    Container(api, "API aplikace", "Node.js, Koa", "Poskytuje REST API pro všechny interakce a obsahuje veškterou logiku aplikace.", "nodejs")
}

System_Ext(gmail, "Gmail SMTP", "Externí SMTP server pro odesílání emailů.", "mail")
System_Ext(mapy, "Mapy.cz API", "Externí API poskytující našeptávání adres.", "map")
System_Ext(ares, "ARES REST API", "Externí API pro získávání údajů o právnických osobách.", "server")
System_Ext(mongo, "MongoDB Atlas", "Externí databáze hostovaná v MongoDB Atlas.", "mongodb")

Rel(user, spa_user, "Používá", "HTTPS")
Rel(public, spa_user, "Používá", "HTTPS")
Rel(admin, spa_admin, "Používá", "HTTPS")

Rel(spa_user, api, "API požadavky", "HTTPS")
Rel(spa_admin, api, "API požadavky", "HTTPS")

Rel(api, gmail, "Žádá o odeslání emailu", "SMTP")
Rel(api, mapy, "Žádá o adresní našeptávání", "HTTPS")
Rel(api, ares, "Žádá o údaje o právnických osobách", "HTTPS")
Rel(api, mongo, "Ukládá a získává data", "TLS/SSL")

Rel(gmail, user, "Odesílá emaily", "SMTP")

Lay_D(user, spa_user)
Lay_D(zohan_system, gmail)
Lay_D(user, gmail)

@enduml
